### ISSUE TITLE
Benchmarking numbers

### ISSUE THREAD

**Issue by rainerborene** [phlex-ruby/phlex#552]
> Rendering a Phlex view is significantly faster than rendering an ActionView partial or ViewComponent component.

I can't find the benchmarking numbers. Where are they?

**Comment by willcosgrove** [comment]
I don't think there is a repo with up to date benchmarking numbers, but there's a pretty recent discussion where some benchmarks were run: https://github.com/orgs/phlex-ruby/discussions/443#discussioncomment-4933946

The quick summation is Phlex faster than ActionView and ViewComponent because of the overhead those frameworks have when rendering a template, ActionView more so than ViewComponent.

Phlex by itself is not as fast a compiled HAML template, but given that the compiled HAML template is normally being called via ActionView or ViewComponent, Phlex still winds up being faster for most real world use cases.

There is a project in development to compile Phlex views at joeldrapper/phlex-compiler [joeldrapper/phlex-compiler](https://github.com/joeldrapper/phlex-compiler) which would bring it's raw rendering performance on par with HAML. Though work on this is waiting at the moment for the [syntax_tree](https://github.com/ruby-syntax-tree/syntax_tree) API to stabilize.
