### ISSUE TITLE
Prevent CSV injection attacks

### ISSUE THREAD

**Issue by joeldrapper** [phlex-ruby/phlex#661]
See: 
1. https://owasp.org/www-community/attacks/CSV_Injection
3. http://georgemauer.net/2017/10/07/csv-injection.html

**Comment by willcosgrove** [comment]
Wow, that's nuts, good find!

On one hand, it's cool that using Phlex::CSV means this has been thought about already and I'm protected against it. On the other, if I'm porting an export from Ruby's plain ol' CSV output, to Phlex::CSV, there's the possibility I could subtly break something.

Probably our best bet is to document that we protect against this, and note how to opt out.

I would imagine if you're opting out, you want to opt out for that whole class, not just at render time. So we could either have a different parent class, or an include that handles it.

```rb
class UsersCSV < Phlex::CSV::Raw
  # ...
end
```

or

```rb
class UsersCSV < Phlex::CSV
  include Phlex::CSV::Raw
end
```

**Comment by willcosgrove** [comment]
Could we make it so that raising if `prevent_csv_injection` isn't defined only happens if there's a case where the CSV injection protection would kick in?

I would imagine in a lot of cases this never comes up. It would be a bummer to have to define a method in every class for a rare scenario.

**Comment by joeldrapper** [comment]
The problem with that is it might not be until your app is in production at 2am over the weekend that a value triggers the escape.

**Comment by willcosgrove** [comment]
I just got off the phone with @thewatts where we discussed this problem at length. He brought up a good point: assuming that this attack is as dangerous as we all think it is, and assuming that the false positive rate is low like we suspect it is, then it seems like the best default option **is** to raise at runtime. 

>it might not be until your app is in production at 2am over the weekend that a value triggers the escape

If that happens, I *want* to be notified. Even if it's at 2am on the weekend. If someone has injected data into my app that causes us to export a CSV with a function that is going to try and exfiltrate all the data in that export, I want to know about it.

So the "aha" for me was that there are three possible desirable outcomes for the `prevent_csv_injection?` method

1. `true` - I expect that there might be injection attacks and in that case I want them escaped so that no harm comes to someone opening the output of this report
2. `false` - I expect that there might be injection attacks but I will be evaluating the contents of this report safely and I am not worried about the attack when viewing in a spreadsheet program
3. `raise` - I do not expect there to be any injection attacks, but if there are any, I want to be notified about it

And my issue with forcing people to define the method to decide, is that I think 100% of the CSV reports I have written, I would have opted in to option 3, raising if we encounter any potentially malicious data.

**Comment by bradgessler** [comment]
Mentioned this in chat, but an opportunity to simplify the code could be to replace the configuration methods with just methods like this:

```ruby
class Phlex::CSV
  def sanitize(value) = prevent_csv_injection trim_whitespace value
end
```

For interchange CSVs where nothing should happen to a value, something like this would be done:

```ruby
class Phlex::CSV
  def sanitize(value) = value
end
```

The `sanitize` method name could probably be improved, but the important thing is that all values are pumped through a method that can do whatever process needs to happen for that value.

Maybe for exceptions to `sanitize`, which handles *all* values by default, a block could be passed into `column` that does stuff to a value, like this:

```ruby
class Phlex::CSV
  def sanitize(value) = prevent_csv_injection trim_whitespace value
  def template(data)
    column "Foo", data.bar do |value|
       # Does nothing to the CSV and bypasses the `sanitize` method.
       unescaped value
    end
    column "Fizz", data.buzz do |value|
       # Only trims whitespace, leaves injections
       trim_whitespace value
    end
  end
end
```
