### ISSUE TITLE
Figure out how to handle string based id keys when selective rendering

### ISSUE THREAD

**Issue by joeldrapper** [phlex-ruby/phlex#694]
When doing selective rendering, we currently look for the `[:id]` key in the attributes Hash. This doesn’t account for attributes that use string values for ids.

Two options I can think of:

1. Looks for `[:id]` and `["id"]` — this has a performance cost, and it still doesn’t technically cover all the “valid HTML” cases such as `"iD"`, `"Id"`, "ID", `:iD`, `:Id`, `:ID`.
2. Require `id`s to be passed as lower-case symbols — we can enforce this in `__attributes__`, which is cached so won’t have much of a performance overhead.

Option 2 is technically a breaking change, if we raise. Perhaps for 1.10, we should just note that selective rendering only works if you use `:id` as a lowercase Symbol. We can start enforcing it in 2.0 by raising from `__attributes__`.

**Comment by dhnaranjo** [comment]
Option 3: Option 2 but kick selective rendering to 2.0 as well, because documentation isn't real but support requests are.

**Comment by willcosgrove** [comment]
My immediate reaction is the same as @dhnaranjo.

* I don't think it's worth the performance cost to check/normalize against all `id` key permutations.
* I am failing to come up with any good reason why someone would want to or need to specify an ID by any other way than `:id` with the possible exception of `"id"`. So I think forcing ID to be a symbol key is a reasonable breaking change.
* Selective rendering is going to be a great headline feature, and it seems like it deserves a 2.0 release rather than a 1.10 release. I'm not one to suggest artificially holding back cool new stuff, but if there's a good reason to, like a breaking change being required, then I'm good to hold it back. And there's no reason why 2.0 needs to be far behind 1.10.

If anyone has any thoughts on use cases for an ID being specified any other way than by `:id` I'd love to see it!

**Comment by joeldrapper** [comment]
I can't think of any real use cases for that. Perhaps if you've loaded some attributes form JSON, it would be convenient to support `"id"`. But it wouldn't be difficult to fix in application code.

Let’s mark Selective Rendering as experimental and remove the implicit `Turbo-Frame` use-case. `X-Fragment` can still work but only supporting lowercase Symbol ids.

**Comment by bradgessler** [comment]
The JSON attributes or a hash object with string keys is the only thing I can think of that resembles a real-world use case.

I think the more interesting question is how to make the `:id` symbol key not surprising. Should all keys be required to be lowercase symbols for the sake of consistency? If so, how would keys outside of that specification be handled in a performant manner? Is there a “dev mode” that detects this and throws and except for non-spec attributes?

**Comment by joeldrapper** [comment]
> Should all keys be required to be lowercase symbols for the sake of consistency?

I think it‘s reasonable to require `id` to be lowercase without any such requirements for other attributes. I’d be okay requiring all symbols to be lower case, while allowing strings to be uppercase. But we’d still need to special-case string ids.

**Comment by joeldrapper** [comment]
Closing this as solved. The plan is to make a breaking change in 2.0 (#695) and have this be an experimental feature in 1.10 with limited support.

**Comment by bradgessler** [comment]
Another thought: include a method called `symbolize` that will symbolize the keys for the JSON use case.

**Comment by joeldrapper** [comment]
I think `.transform_keys(&:to_sym)` will be fine for the JSON use-case.
