### ISSUE TITLE
Rendering Phlex Views like Rails partials

### ISSUE THREAD

**Issue by reeganviljoen** [phlex-ruby/phlex#754]
It would be amazing for if Phlex Views could be rendered like partials

e.g instead of:
```
render Nav.new
```

being able to call the Phlex view like a partial
```
render 'nav'
```

The main benefit here is it would make this amazing library even more accessible to the larger Ruby on Rails community

**Comment by reeganviljoen** [comment]
@joeldrapper I was inspired by your collaboration in the larger [Rails community](https://github.com/ViewComponent/view_component/issues/618), so I wrote a gem(still pre-release) off the back of @joelhawksley pr into [Rails]([joelhawksley](https://github.com/joelhawksley))

I hope this can be a helpful starting point to help Phlex be more accessible to the wider community

**Comment by joeldrapper** [comment]
Hey, thanks for opening the issue. Couple of initial thoughts:

Firstly, I don’t think we should support this style `render 'nav'` for a few reasons:

- We already support `render Nav.new` (and if you don’t need to pass any arguments, `render Nav`).
- This style is conceptually simpler because if you understand how Ruby resolves constants, you know exactly which component will be rendered.
- Language servers such as Solargraph, RubyLSP and RubyMine’s internal thingy can provide autocomplete as you’re typing the constant as well as jump to definition.
- There is no need for any kind of string manipulation/inflection or managing our own relative constant resolution logic. Which constant does `"nav"` map to? We would probably need to take the current module, split it at `"::"` and walk up looking for matches. In the end, this would be subtly different to Ruby’s own relative constant lookup, which is _lexical_.
- Also, this would be a significant performance overhead without caching the resolution in a hash map, and if we did cache, we would need to invalidate that cache whenever new modules are added in places that might impact the module resolution.
- Finally, with `Phlex::Kit` there's also another style that is even simpler than `render Nav do`, `render Nav.new do` or `render "nav" do`. With Phlex::Kits, you can do just `Nav do`. See details of this experimental feature here. https://github.com/phlex-ruby/phlex/releases/tag/1.10.0

That said, I am interested in supporting something like `render @post` where there is some kind of mapping from the `Post` object to a component that can render that post object. I think that's more what the view component discussion was about unless I’ve missed something.

**Comment by joeldrapper** [comment]
One additional thought: Phlex’s own `render` method is meant to be as flexible as possible. `render "nav"` in Phlex (not `phlex-rails`) actually renders the literal text `"nav"`. This is useful polymorphism because it allows you to create components that accept arguments that can either be provided as strings or other renderables.

If I have a component like this:

```ruby
class Box < Phlex::HTML
  def initialize(content:)
    @content = content
  end

  def view_template
    div(class: "box") { render @content }
  end
end
```

I can render it with a component:
```ruby
render Box.new(
  content: SomeOtherComponent.new
)
```

or a string
```ruby
render Box.new(
  content: "Literally a string"
)
```

It also works with an enumerable of any renderable.

In `phlex-rails` we're hoping to support rendering strings like this and allowing you to render partials explicitly with the `partial:` keyword argument. See this PR https://github.com/phlex-ruby/phlex-rails/pull/149 and associated Rails issue that has so far held up this PR https://github.com/rails/rails/issues/51015

**Comment by thedumbtechguy** [comment]
> That said, I am interested in supporting something like render @post where there is some kind of mapping from the Post object to a component that can render that post object. I think that's more what the view component discussion was about unless I’ve missed something.

You could do that by registering a template engine e.g. https://github.com/slim-template/slim-rails/blob/master/lib/slim-rails/register_engine.rb

**Comment by reeganviljoen** [comment]
> You could do that by registering a template engine e.g. https://github.com/slim-template/slim-rails/blob/master/lib/slim-rails/register_engine.rb

@thedumbtechguy Not really, it let's you render a different template, but how do you translate @posts to PostView

@joeldrapper I will add this functionality this weekend, I am also going to put all the other render 'modes' behind a config so you can choose what you want to use, dies that sound good?

**Comment by joeldrapper** [comment]
> I will add this functionality this weekend, I am also going to put all the other render 'modes' behind a config so you can choose what you want to use, does that sound good?

Being able to use `render @post` is something we should develop carefully with the view component team, probably sharing the same common gem and implementing the same interfaces.

I don’t know what render modes you mean. I’m not keen on introducing configuration for render modes. Instead, we have a flexible `render` method that can render lots of different things.

**Comment by joeldrapper** [comment]
Closing this as I don’t think any action is needed. We should probably open a new issue in the `phlex-rails` repo to address implicit rendering of resources (`render @posts` and `render @post`).
